[package]
name = "rdog_lib"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
bytemuck = { workspace = true }
spirv-std = { workspace = true }
glam = { version = "0.29", default-features = false, features = ["bytemuck"] }
